version: 2

defaults: &defaults
  docker:
    - image: circleci/clojure:boot-2.7.2
  working_directory: ~/boot-cljfmt

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: boot-cljfmt-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - run: boot test
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: boot-cljfmt-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - persist_to_workspace:
          root: .
          paths: .
    environment:
      BOOT_JVM_OPTIONS: "-Xms512m -Xmx1024m"
      BOOT_WATCHERS_DISABLE: "yes"
  deploy:
    <<: *defaults
    requires:
      - build
    filters:
      branches:
        only: /master/
    steps:
      - attach_workspace:
          at: ~/boot-cljfmt
      - run: boot build-jar push-release

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
