version: 2

defaults: &defaults
  docker:
    - image: circleci/clojure:boot-2.7.2
  working_directory: ~/boot-cljfmt

jobs:
  build:
    steps:
      - checkout
      - restore_cache:
          key: boot-cljfmt-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - run: boot test
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: boot-cljfmt-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - parsist_to_workspace:
          root: .
          paths: .
    environment:
      BOOT_JVM_OPTIONS: "-Xms512m -Xmx1024m"
      BOOT_WATCHERS_DISABLE: "yes"
  deploy:
    requires:
      - build
    filters:
      branches:
        only: /master/
    steps:
      - attach_workspace:
          at: ~/boot-cljfmt
      - run: boot build-jar push-release
